<a href="https://colab.research.google.com/github/regitaaft/iris-eda-ml/blob/main/ML_tugas_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loan Approval
Loan approval adalah data tentang pengajuan pinjaman (kredit) seseorang ke bank/lembaga keuangan dan apakah pengajuan itu disetujui atau ditolak.
### Tujuan
memprediksi apakah seseorang layak dapat pinjaman atau tidak

### import library

In [ ]:
# Library dasar
import pandas as pd
import numpy as np

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing & split data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Model
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Boosting
from xgboost import XGBClassifier

pandas → baca & olah data

numpy → operasi numerik

sklearn → machine learning

RandomForest → bagging

XGBoost → boosting

MLPClassifier → neural network

### Load Dataset

In [ ]:
df = pd.read_csv('loan_data_set.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

Dataset yang digunakan dalam penelitian ini adalah Loan Approval Dataset yang berisi data karakteristik pemohon pinjaman.

Berdasarkan output di atas, dapat dilihat bahwa dataset terdiri dari beberapa variabel, antara lain:

1.  ApplicantIncome: pendapatan pemohon
2.   LoanAmount: jumlah pinjaman yang diajukan
3. Credit_History: riwayat kredit pemohon
4. Dependents: jumlah tanggungan yang dimiliki pemohon (misalnya anak atau keluarga yang dibiayai)
5. Education: tingkat pendidikan pemohon (Graduate = lulusan sarjana, Not Graduate = bukan sarjana)
6. Self_Employed: status pekerjaan pemohon (Yes = wiraswasta, No = bukan wiraswasta)
7. Loan_Status: status persetujuan pinjaman (target), dengan kategori Y (disetujui) dan N (ditolak)

### Cek Data

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

### Data Cleaning

In [ ]:
df.fillna(df.mode().iloc[0], inplace=True)

### Encoding

In [ ]:
le = LabelEncode()

for col in df.select.dftypes(include='object').columns:
  df[col]=le.fit_transform(df[col])

NameError: name 'LabelEncode' is not defined